name: setup-build-env
description: Setup Building Environment
inputs:
  # be consistent with the caller workflow
  clang_version:
    description: 'clang version, see https://apt.llvm.org/'
    required: false
    # use the stable branch, empty for the development branch
    default: 18
    type: string
  install_clang_tool:
    description: 'install clang-tool'
    required: false
    default: false
    type: boolean
  install_clang_tidy:
    description: 'install clang-tidy'
    required: false
    default: false
    type: boolean

runs:
  using: 'composite'
  steps:
    - name: Add scylla-ppa repo
      shell: bash
      run: |
        sudo add-apt-repository ppa:scylladb/ppa

    - name: Add clang apt repo
      if: ${{ inputs.install_clang_tool || inputs.install_clang_tidy }}
      shell: bash
      run: |
        sudo apt-get install -y curl
        curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc >/dev/null
        repo_component=llvm-toolchain-jammy
        # use the development branch if clang_version is empty
        if [ -n "${{ inputs.clang_version }}" ]; then
            repo_component+=-${{ inputs.clang_version }}
        fi
        echo "deb http://apt.llvm.org/jammy/ $repo_component main" | sudo tee -a /etc/apt/sources.list.d/llvm.list
        sudo apt-get update

    - name: Install clang-tools
      if: ${{ inputs.install_clang_tools }}
      shell: bash
      run: |
        pkg=clang-tools
        if [ -n "${{ inputs.clang_version }}" ]; then
          pkg+=-${{ inputs.clang_version }}
        fi
        sudo apt-get install -y $pkg

    - name: Install clang-tidy
      if: ${{ inputs.install_clang_tidy }}
      shell: bash
      run: |
        pkg=clang-tidy
        if [ -n "${{ inputs.clang_version }}" ]; then
          pkg+=-${{ inputs.clang_version }}
        fi
        sudo apt-get install -y $pkg

    - name: Install GCC-13
      # ubuntu:jammy comes with GCC-11. and libstdc++-11 fails to compile
      # scylla which defines value type of std::unordered_map in .cc
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get install -y libstdc++-13-dev

    - name: Install more build dependencies
      shell: bash
      run: |
        # - do not install java dependencies, which is not only not necessary,
        #   and they include "python", which is not EOL and not available.
        # - replace "scylla-libthrift010" with "libthrift-dev". because
        #   scylla-libthrift010 : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
        # - we don't perform tests, so minio is not necessary.
        sed -i.orig \
          -e '/tools\/.*\/install-dependencies.sh/d' \
          -e 's/scylla-libthrift010-dev/libthrift-dev/' \
          -e 's/(minio_download_jobs)/(true)/' \
          ./install-dependencies.sh
        sudo ./install-dependencies.sh
        mv ./install-dependencies.sh{.orig,}
        # for ld.lld
        pkg=lld
        if [ -n "${{ inputs.clang_version }}" ]; then
          pkg+=-${{ inputs.clang_version }}
        fi
        sudo apt-get install -y $pkg

    - name: Install {fmt} using cooking.sh
      shell: bash
      run: |
        sudo apt-get remove -y libfmt-dev
        seastar/cooking.sh -d build-fmt -p cooking -i fmt
