name: codespell
on:
  pull_request:
    branches:
      - master
      - enterprise
permissions: {}
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "ser"
          skip: "./.git,build/*,tools/*,*.js,*.thrift"
