name: iwyu

on:
  pull_request:
    branches:
      - master

env:
  CLANG_VERSION: 18
  BUILD_TYPE: RelWithDebInfo
  BUILD_DIR: build
  CLEANER_OUTPUT_PATH: build/clang-include-cleaner.log

permissions: {}

jobs:
  clang-include-cleaner:
    name: "Analyze #includes in source files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install clang-tools
        run: |
          sudo apt-get install -y curl
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc >/dev/null
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main" | sudo tee -a /etc/apt/llvm.list
          sudo add-apt-repository ppa:scylladb/ppa
          sudo apt update
          sudo ./install-dependencies.sh
          sudo apt-get install -y libsystemd-dev antlr3 libyaml-cpp-dev
          sudo apt-get install -y clang-tools-$CLANG_VERSION
      - name: Generate compilation database
        run: |
          cmake                                 \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE      \
            -DCMAKE_C_COMPILER=clang            \
            -DCMAKE_CXX_COMPILER=clang++        \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  \
            -G Ninja                            \
            -B $BUILD_DIR                       \
            -S .
      - name: clang-include-cleaner
        run: |
          # TODO: run multi-threaded
          find $PWD -name "*.cc" -o -name ".hh" | \
            xargs -t -n 1 \
            clang-include-cleaner-$CLANG_VERSION --print=changes -p $BUILD_DIR > $CLEANER_OUTPUT_PATH 2>&1
      - uses: actions/upload-artifact@v4
        with:
          name: Logs (clang-include-cleaner)
          path: "./${{ env.CLEANER_OUTPUT_PATH }}"
